"""add client conversion_goal

Revision ID: 10c023269e3c
Revises: 762d503b4725
Create Date: 2026-06-19 09:13:35.678510

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c023269e3c'
down_revision: str | None = '762d503b4725'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('conversion_goal', sa.String(length=50), server_default='purchase', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'conversion_goal')
    # ### end Alembic commands ###
