"""client multi emails + contact phone

Revision ID: 248acfdc7800
Revises: 6cbc25e9bb60
Create Date: 2026-06-19 13:59:26.857013

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248acfdc7800'
down_revision: str | None = '6cbc25e9bb60'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('contact_name', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('emails', sa.JSON(), nullable=False))
    op.drop_index('ix_clients_recipient_email', table_name='clients')
    op.drop_column('clients', 'recipient_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('recipient_email', sa.VARCHAR(length=150), nullable=False))
    op.create_index('ix_clients_recipient_email', 'clients', ['recipient_email'], unique=False)
    op.drop_column('clients', 'emails')
    op.drop_column('clients', 'phone')
    op.drop_column('clients', 'contact_name')
    # ### end Alembic commands ###
