"""add client meta_business_id

Revision ID: 6cbc25e9bb60
Revises: 10c023269e3c
Create Date: 2026-06-19 12:51:16.176057

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbc25e9bb60'
down_revision: str | None = '10c023269e3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('meta_business_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'meta_business_id')
    # ### end Alembic commands ###
