"""add meta portfolios and ad accounts

Revision ID: e04ab58d37cc
Revises: b483acf977ea
Create Date: 2026-06-19 19:05:32.175012

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04ab58d37cc'
down_revision: str | None = 'b483acf977ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_portfolios',
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('meta_ad_accounts',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('account_status', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.String(length=100), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['meta_portfolios.business_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_ad_accounts_business_id'), 'meta_ad_accounts', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_ad_accounts_business_id'), table_name='meta_ad_accounts')
    op.drop_table('meta_ad_accounts')
    op.drop_table('meta_portfolios')
    # ### end Alembic commands ###
